---
- name: Converge
  hosts:
    - subjects
  tasks:
    - name: Import MDT drivers
      trippsc2.mdt.import_drivers:
        mdt_share_path: C:\MDTShare
        source_paths:
          - C:\Drivers
        path: Out-of-Box Drivers\WinPE
 
    - name: Import MDT drivers
      trippsc2.mdt.import_drivers:
        mdt_share_path: C:\MDTShare
        source_paths:
          - C:\Drivers
        path: Out-of-Box Drivers\Windows 10

    - name: Import MDT drivers with duplicates
      trippsc2.mdt.import_drivers:
        mdt_share_path: C:\MDTShare
        source_paths:
          - C:\Drivers
        path: Out-of-Box Drivers\WinPE
        import_duplicates: true
      tags:
        - always
        - molecule-idempotence-notest
