---
- name: Prepare
  hosts:
    - subjects
  tasks:
    - name: Install MDT
      chocolatey.chocolatey.win_chocolatey:
        name:
          - windows-adk-all
          - mdt
        state: present

    - name: Create temporary directories
      loop:
        - C:\Drivers
        - C:\temp
      ansible.windows.win_file:
        path: "{{ item }}"
        state: directory

    - name: Create MDT Deployment Share
      trippsc2.mdt.deployment_share:
        path: C:\MDTShare
        description: MDT Deployment Share
        share_name: MDTShare
        state: present

    - name: Add permissions to MDT Deployment Share
      ansible.windows.win_acl:
        path: C:\MDTShare
        user: vagrant
        rights: FullControl
        type: allow

    - name: Pre-create MDT directories
      loop:
        - name: Windows 10
          parent_directory: Out-of-Box Drivers
        - name: WinPE
          parent_directory: Out-of-Box Drivers
      trippsc2.mdt.directory:
        name: "{{ item.name }}"
        parent_directory: "{{ item.parent_directory }}"
        mdt_directory_path: C:\MDTShare
        state: present

    - name: Download Dell drivers
      trippsc2.dell.win_dell_driver_pack:
        catalog_temp_path: C:\temp
        download_path: C:\Drivers
        os: winpe_11
