---
- name: Converge
  hosts:
    - subjects
  tasks:
    - name: Get Operating Systems directory info
      trippsc2.mdt.directory_info:
        path: Operating Systems
        mdt_share_path: C:\MDTShare
      register: _os_directory

    - name: Verify Operating Systems directory
      ansible.builtin.assert:
        that:
          - _os_directory.exists
          - _os_directory.directory.enabled
          - _os_directory.directory.type == 'operating_system_folder'
          - _os_directory.directory.name == 'Operating Systems'
          - _os_directory.directory.contents | length == 1
        fail_msg: The Operating Systems directory is not valid.
        success_msg: The Operating Systems directory is valid.

    - name: Verify Windows 10 child directory
      ansible.builtin.assert:
        that:
          - _os_directory.directory.contents[0].enabled
          - _os_directory.directory.contents[0].type == 'operating_system_folder'
          - _os_directory.directory.contents[0].name == 'Windows 10'
        fail_msg: The Windows 10 child directory is not valid.
        success_msg: The Windows 10 child directory is valid.

    - name: Get Out-of-Box Drivers directory info
      trippsc2.mdt.directory_info:
        path: Out-of-Box Drivers
        mdt_share_path: C:\MDTShare
      register: _drivers_directory

    - name: Verify Out-of-Box Drivers directory
      ansible.builtin.assert:
        that:
          - _drivers_directory.exists
          - _drivers_directory.directory.enabled
          - _drivers_directory.directory.type == 'driver_folder'
          - _drivers_directory.directory.name == 'Out-of-Box Drivers'
        fail_msg: The Out-of-Box Drivers directory is not valid.
        success_msg: The Out-of-Box Drivers directory is valid.

    - name: Select DriverFolder contents
      ansible.builtin.set_fact:
        _driver_subdirectories: >-
          {{ _drivers_directory.directory.contents |
              selectattr('type', 'equalto', 'driver_folder') |
              list }}
        _driver_contents: >-
          {{ _drivers_directory.directory.contents |
              selectattr('type', 'equalto', 'driver') |
              list }}
    
    - name: Verify Out-of-Box Drivers contents
      ansible.builtin.assert:
        that:
          - _driver_subdirectories | length == 1
          - _driver_subdirectories[0].enabled
          - _driver_subdirectories[0].name == 'WinPE'
          - _driver_contents | length == (_drivers_directory.directory.contents | length - 1)
        fail_msg: The Out-of-Box Drivers contents are not valid.
        success_msg: The Out-of-Box Drivers contents are valid.
