---
- name: Verify
  hosts:
    - subjects
  tasks:
    - name: Attempt to not supply MDT share path
      trippsc2.mdt.task_sequence:
        id: TEST
        name: Test
        template: Client.xml
        operating_system_name: Windows 11 Enterprise
        full_name: Test User
        organization: Test Organization
        state: present
      register: _no_mdt_share_path
      ignore_errors: true

    - name: Verify that MDT share path is required
      ansible.builtin.assert:
        that:
          - _no_mdt_share_path is failed
          - '_no_mdt_share_path.msg == "missing required arguments: mdt_share_path"'
        fail_msg: MDT share path is required.
        success_msg: MDT share path is required.

    - name: Attempt to supply non-existent MDT share path
      trippsc2.mdt.task_sequence:
        mdt_share_path: C:\Test
        id: TEST
        name: Test
        template: Client.xml
        operating_system_name: Windows 11 Enterprise
        full_name: Test User
        organization: Test Organization
        state: present
      register: _nonexistent_mdt_share_path
      ignore_errors: true

    - name: Verify that previous task fails
      ansible.builtin.assert:
        that:
          - _nonexistent_mdt_share_path is failed
          - '_nonexistent_mdt_share_path.msg == "MDT share path ''C:\Test'' does not exist."'
        fail_msg: The task should fail when the MDT share path does not exist.
        success_msg: The task failed as expected when the MDT share path does not exist.

    - name: Attempt to supply no name or ID
      trippsc2.mdt.task_sequence:
        mdt_share_path: C:\MDTShare
        template: Client.xml
        operating_system_name: Windows 11 Enterprise
        full_name: Test User
        organization: Test Organization
        state: present
      register: _no_name_or_id
      ignore_errors: true

    - name: Verify that the module fails when no name or ID is supplied
      ansible.builtin.assert:
        that:
          - _no_name_or_id is failed
          - '_no_name_or_id.msg == "one of the following is required: name, id"'
        fail_msg: The module did not fail when no name or ID was supplied.
        success_msg: The module failed when no name or ID was supplied, as expected.

    - name: Attempt to supply too long ID
      trippsc2.mdt.task_sequence:
        mdt_share_path: C:\MDTShare
        id: MoreThanSixteenCharacters
        name: Test
        template: Client.xml
        operating_system_name: Windows 11 Enterprise
        full_name: Test User
        organization: Test Organization
        state: present
      register: _too_long_id
      ignore_errors: true

    - name: Verify that the module fails when the ID is too long
      ansible.builtin.assert:
        that:
          - _too_long_id is failed
          - '_too_long_id.msg == "The value of the parameter ''id'' cannot exceed 16 characters."'
        fail_msg: The module did not fail when the ID was too long.
        success_msg: The module failed when the ID was too long, as expected.

    - name: Attempt to provide non-existent Operating System
      trippsc2.mdt.task_sequence:
        mdt_share_path: C:\MDTShare
        id: TEST
        name: Test
        template: Client.xml
        operating_system_name: Non-existent
        full_name: Test User
        organization: Test Organization
        state: present
      register: _nonexistent_operating_system
      ignore_errors: true

    - name: Verify that the module fails when the Operating System does not exist
      ansible.builtin.assert:
        that:
          - _nonexistent_operating_system is failed
          - '_nonexistent_operating_system.msg == "No MDT operating system found with name ''Non-existent''."'
        fail_msg: The module did not fail when the Operating System does not exist.
        success_msg: The module failed when the Operating System does not exist, as expected.

    - name: Attempt to provide non-existent template
      trippsc2.mdt.task_sequence:
        mdt_share_path: C:\MDTShare
        id: TEST
        name: Test
        template: Nonexistent.xml
        operating_system_name: Windows 11 Enterprise
        full_name: Test User
        organization: Test Organization
        state: present
      register: _nonexistent_template
      ignore_errors: true

    - name: Verify that the module fails when the template does not exist
      ansible.builtin.assert:
        that:
          - _nonexistent_template is failed
          - '_nonexistent_template.msg == "No MDT task sequence template found with name ''Nonexistent.xml''."'
        fail_msg: The module did not fail when the template does not exist.
        success_msg: The module failed when the template does not exist, as expected.
