---
- name: Converge
  hosts:
    - subjects
  tasks:
    - name: Check MDT directory
      check_mode: true
      trippsc2.mdt.directory:
        mdt_share_path: C:\MDTShare
        path: Operating Systems\Windows 10
        state: present

    - name: Create MDT directory
      trippsc2.mdt.directory:
        mdt_share_path: C:\MDTShare
        path: Operating Systems\Windows 10
        state: present

    - name: Check MDT directory
      check_mode: true
      trippsc2.mdt.directory:
        mdt_share_path: C:\MDTShare
        path: Operating Systems\Windows 11
        state: present

    - name: Create MDT directory
      trippsc2.mdt.directory:
        mdt_share_path: C:\MDTShare
        path: Operating Systems\Windows 11
        state: present

    - name: Check MDT directory
      check_mode: true
      trippsc2.mdt.directory:
        mdt_share_path: C:\MDTShare
        path: Operating Systems\Windows 12
        state: absent

    - name: Remove MDT directory
      trippsc2.mdt.directory:
        mdt_share_path: C:\MDTShare
        path: Operating Systems\Windows 12
        state: absent

    - name: Check MDT directory
      check_mode: true
      trippsc2.mdt.directory:
        mdt_share_path: C:\MDTShare
        path: Out-of-Box Drivers\WinPE
        state: absent

    - name: Remove MDT directory
      trippsc2.mdt.directory:
        mdt_share_path: C:\MDTShare
        path: Out-of-Box Drivers\WinPE
        state: absent
