---
- name: Prepare
  hosts:
    - subjects
  tasks:
    - name: Install MDT
      chocolatey.chocolatey.win_chocolatey:
        name:
          - windows-adk-all
          - mdt
        state: present

    - name: Create MDT Deployment Share
      trippsc2.mdt.deployment_share:
        path: C:\MDTShare
        description: MDT Deployment Share
        share_name: MDTShare
        state: present

    - name: Add permissions to MDT Deployment Share
      ansible.windows.win_acl:
        path: C:\MDTShare
        user: vagrant
        rights: FullControl
        type: allow

    - name: Pre-create MDT directories
      loop:
        - Operating Systems\Windows 10
        - Out-of-Box Drivers\WinPE
        - Out-of-Box Drivers\WinPE\Dell
      trippsc2.mdt.directory:
        path: "{{ item }}"
        mdt_share_path: C:\MDTShare
        state: present
