---
- name: Converge
  hosts:
    - subjects
  tasks:
    - name: Check existing share
      check_mode: true
      diff: true
      trippsc2.mdt.deployment_share:
        installation_path: C:\Program Files\Microsoft Deployment Toolkit
        mdt_share_path: C:\MDTShare1
        description: MDT Deployment Share 1
        unc_path: "\\\\{{ inventory_hostname | upper }}\\MDTShare1$"
        state: present

    - name: Create existing share
      diff: true
      trippsc2.mdt.deployment_share:
        installation_path: C:\Program Files\Microsoft Deployment Toolkit
        mdt_share_path: C:\MDTShare1
        description: MDT Deployment Share 1
        unc_path: "\\\\{{ inventory_hostname | upper }}\\MDTShare1$"
        state: present

    - name: Check un-added share
      check_mode: true
      diff: true
      trippsc2.mdt.deployment_share:
        installation_path: C:\Program Files\Microsoft Deployment Toolkit
        mdt_share_path: C:\MDTShare2
        description: MDT Deployment Share 2
        unc_path: "\\\\{{ inventory_hostname | upper }}\\MDTShare2$"
        state: present

    - name: Create un-added share
      diff: true
      trippsc2.mdt.deployment_share:
        installation_path: C:\Program Files\Microsoft Deployment Toolkit
        mdt_share_path: C:\MDTShare2
        description: MDT Deployment Share 2
        unc_path: "\\\\{{ inventory_hostname | upper }}\\MDTShare2$"
        state: present

    - name: Check existing share
      check_mode: true
      diff: true
      trippsc2.mdt.deployment_share:
        installation_path: C:\Program Files\Microsoft Deployment Toolkit
        mdt_share_path: C:\MDTShare3
        state: absent

    - name: Remove existing share
      diff: true
      trippsc2.mdt.deployment_share:
        installation_path: C:\Program Files\Microsoft Deployment Toolkit
        mdt_share_path: C:\MDTShare3
        state: absent

    - name: Check non-existent share
      check_mode: true
      diff: true
      trippsc2.mdt.deployment_share:
        installation_path: C:\Program Files\Microsoft Deployment Toolkit
        mdt_share_path: C:\MDTShare4
        state: absent

    - name: Remove non-existent share
      diff: true
      trippsc2.mdt.deployment_share:
        installation_path: C:\Program Files\Microsoft Deployment Toolkit
        mdt_share_path: C:\MDTShare4
        state: absent
