---
- name: Prepare
  hosts:
    - subjects
  tasks:
    - name: Install MDT
      chocolatey.chocolatey.win_chocolatey:
        name:
          - windows-adk-all
          - mdt
        state: present

    - name: Create MDT Deployment Share
      loop:
        - MDTShare1
        - MDTShare2
        - MDTShare3
      trippsc2.mdt.deployment_share:
        mdt_share_path: "C:\\{{ item }}"
        description: MDT Deployment Share
        unc_path: "\\\\{{ inventory_hostname | upper }}\\{{ item }}$"
        state: present

    - name: Create SMB share
      loop:
        - MDTShare1
        - MDTShare2
        - MDTShare3
      ansible.windows.win_share:
        name: "{{ item }}$"
        path: "C:\\{{ item }}"
        full: Everyone
        caching_mode: None

    - name: Add permissions to MDT Deployment Share
      loop:
        - C:\MDTShare1
        - C:\MDTShare2
        - C:\MDTShare3
      ansible.windows.win_acl:
        path: "{{ item }}"
        user: vagrant
        rights: FullControl
        type: allow

    - name: Configure MDT deployment share settings
      loop:
        - C:\MDTShare1
        - C:\MDTShare2
        - C:\MDTShare3
      trippsc2.mdt.deployment_share_settings:
        mdt_share_path: "{{ item }}"
        x86:
          enabled: false
        x64:
          generic_iso:
            enabled: true
          generic_wim:
            enabled: true
          litetouch_iso:
            enabled: true
          selection_profile: Nothing
