---
- name: Verify
  hosts:
    - subjects
  tasks:
    - name: Attempt to not supply MDT share path
      trippsc2.mdt.task_sequence_info:
        name: Test
      register: _no_mdt_share_path
      ignore_errors: true

    - name: Verify that MDT share path is required
      ansible.builtin.assert:
        that:
          - _no_mdt_share_path is failed
          - '_no_mdt_share_path.msg == "missing required arguments: mdt_share_path"'
        fail_msg: MDT share path is required.
        success_msg: MDT share path is required.

    - name: Attempt to supply non-existent MDT share path
      trippsc2.mdt.task_sequence_info:
        mdt_share_path: C:\Test
        name: Test
      register: _nonexistent_mdt_share_path
      ignore_errors: true

    - name: Verify that previous task fails
      ansible.builtin.assert:
        that:
          - _nonexistent_mdt_share_path is failed
          - '_nonexistent_mdt_share_path.msg == "MDT share path ''C:\Test'' does not exist."'
        fail_msg: The task should fail when the MDT share path does not exist.
        success_msg: The task failed as expected when the MDT share path does not exist.

    - name: Attempt to supply no name or ID
      trippsc2.mdt.task_sequence_info:
        mdt_share_path: C:\MDTShare
      register: _no_name_or_id
      ignore_errors: true

    - name: Verify that the module fails when no name or ID is supplied
      ansible.builtin.assert:
        that:
          - _no_name_or_id is failed
          - '_no_name_or_id.msg == "one of the following is required: name, id"'
        fail_msg: The module did not fail when no name or ID was supplied.
        success_msg: The module failed when no name or ID was supplied, as expected.

    - name: Attempt to supply both ID and name
      trippsc2.mdt.task_sequence_info:
        mdt_share_path: C:\MDTShare
        id: NONE-NO-ADMIN
        name: No product key
      register: _both_id_and_name
      ignore_errors: true

    - name: Verify that the module fails when both ID and name are supplied
      ansible.builtin.assert:
        that:
          - _both_id_and_name is failed
          - '_both_id_and_name.msg == "parameters are mutually exclusive: name, id"'
        fail_msg: The module did not fail when both ID and name were supplied.
        success_msg: The module failed when both ID and name were supplied, as expected.

    - name: Attempt to supply too long ID
      trippsc2.mdt.task_sequence_info:
        mdt_share_path: C:\MDTShare
        id: MoreThanSixteenCharacters
      register: _too_long_id
      ignore_errors: true

    - name: Verify that the module fails when the ID is too long
      ansible.builtin.assert:
        that:
          - _too_long_id is failed
          - '_too_long_id.msg == "The value of the parameter ''id'' cannot exceed 16 characters."'
        fail_msg: The module did not fail when the ID was too long.
        success_msg: The module failed when the ID was too long, as expected.
